export interface Converter{
    success: boolean
    timestamp: number
    base: string
    date: string
    rates: Rates
}

export interface HistoricalRates {
  success: boolean
  timestamp: number
  historical: boolean
  base: string
  date: string
  rates: Rates
}

  export interface Rates {
    AED: number
    AFN: number
    ALL: number
    AMD: number
    ANG: number
    AOA: number
    ARS: number
    AUD: number
    AWG: number
    AZN: number
    BAM: number
    BBD: number
    BDT: number
    BGN: number
    BHD: number
    BIF: number
    BMD: number
    BND: number
    BOB: number
    BRL: number
    BSD: number
    BTC: number
    BTN: number
    BWP: number
    BYN: number
    BYR: number
    BZD: number
    CAD: number
    CDF: number
    CHF: number
    CLF: number
    CLP: number
    CNY: number
    CNH: number
    COP: number
    CRC: number
    CUC: number
    CUP: number
    CVE: number
    CZK: number
    DJF: number
    DKK: number
    DOP: number
    DZD: number
    EGP: number
    ERN: number
    ETB: number
    EUR: number
    FJD: number
    FKP: number
    GBP: number
    GEL: number
    GGP: number
    GHS: number
    GIP: number
    GMD: number
    GNF: number
    GTQ: number
    GYD: number
    HKD: number
    HNL: number
    HRK: number
    HTG: number
    HUF: number
    IDR: number
    ILS: number
    IMP: number
    INR: number
    IQD: number
    IRR: number
    ISK: number
    JEP: number
    JMD: number
    JOD: number
    JPY: number
    KES: number
    KGS: number
    KHR: number
    KMF: number
    KPW: number
    KRW: number
    KWD: number
    KYD: number
    KZT: number
    LAK: number
    LBP: number
    LKR: number
    LRD: number
    LSL: number
    LTL: number
    LVL: number
    LYD: number
    MAD: number
    MDL: number
    MGA: number
    MKD: number
    MMK: number
    MNT: number
    MOP: number
    MRU: number
    MUR: number
    MVR: number
    MWK: number
    MXN: number
    MYR: number
    MZN: number
    NAD: number
    NGN: number
    NIO: number
    NOK: number
    NPR: number
    NZD: number
    OMR: number
    PAB: number
    PEN: number
    PGK: number
    PHP: number
    PKR: number
    PLN: number
    PYG: number
    QAR: number
    RON: number
    RSD: number
    RUB: number
    RWF: number
    SAR: number
    SBD: number
    SCR: number
    SDG: number
    SEK: number
    SGD: number
    SHP: number
    SLE: number
    SLL: number
    SOS: number
    SRD: number
    STD: number
    SVC: number
    SYP: number
    SZL: number
    THB: number
    TJS: number
    TMT: number
    TND: number
    TOP: number
    TRY: number
    TTD: number
    TWD: number
    TZS: number
    UAH: number
    UGX: number
    USD: number
    UYU: number
    UZS: number
    VES: number
    VND: number
    VUV: number
    WST: number
    XAF: number
    XAG: number
    XAU: number
    XCD: number
    XDR: number
    XOF: number
    XPF: number
    YER: number
    ZAR: number
    ZMK: number
    ZMW: number
    ZWL: number
  }
  export interface SymbolsResponse {
    success: boolean
    symbols: Symbols
  }
  
  export interface Symbols {
    AED: string
    AFN: string
    ALL: string
    AMD: string
    ANG: string
    AOA: string
    ARS: string
    AUD: string
    AWG: string
    AZN: string
    BAM: string
    BBD: string
    BDT: string
    BGN: string
    BHD: string
    BIF: string
    BMD: string
    BND: string
    BOB: string
    BRL: string
    BSD: string
    BTC: string
    BTN: string
    BWP: string
    BYN: string
    BYR: string
    BZD: string
    CAD: string
    CDF: string
    CHF: string
    CLF: string
    CLP: string
    CNY: string
    CNH: string
    COP: string
    CRC: string
    CUC: string
    CUP: string
    CVE: string
    CZK: string
    DJF: string
    DKK: string
    DOP: string
    DZD: string
    EGP: string
    ERN: string
    ETB: string
    EUR: string
    FJD: string
    FKP: string
    GBP: string
    GEL: string
    GGP: string
    GHS: string
    GIP: string
    GMD: string
    GNF: string
    GTQ: string
    GYD: string
    HKD: string
    HNL: string
    HRK: string
    HTG: string
    HUF: string
    IDR: string
    ILS: string
    IMP: string
    INR: string
    IQD: string
    IRR: string
    ISK: string
    JEP: string
    JMD: string
    JOD: string
    JPY: string
    KES: string
    KGS: string
    KHR: string
    KMF: string
    KPW: string
    KRW: string
    KWD: string
    KYD: string
    KZT: string
    LAK: string
    LBP: string
    LKR: string
    LRD: string
    LSL: string
    LTL: string
    LVL: string
    LYD: string
    MAD: string
    MDL: string
    MGA: string
    MKD: string
    MMK: string
    MNT: string
    MOP: string
    MRU: string
    MUR: string
    MVR: string
    MWK: string
    MXN: string
    MYR: string
    MZN: string
    NAD: string
    NGN: string
    NIO: string
    NOK: string
    NPR: string
    NZD: string
    OMR: string
    PAB: string
    PEN: string
    PGK: string
    PHP: string
    PKR: string
    PLN: string
    PYG: string
    QAR: string
    RON: string
    RSD: string
    RUB: string
    RWF: string
    SAR: string
    SBD: string
    SCR: string
    SDG: string
    SEK: string
    SGD: string
    SHP: string
    SLE: string
    SLL: string
    SOS: string
    SRD: string
    STD: string
    SVC: string
    SYP: string
    SZL: string
    THB: string
    TJS: string
    TMT: string
    TND: string
    TOP: string
    TRY: string
    TTD: string
    TWD: string
    TZS: string
    UAH: string
    UGX: string
    USD: string
    UYU: string
    UZS: string
    VEF: string
    VES: string
    VND: string
    VUV: string
    WST: string
    XAF: string
    XAG: string
    XAU: string
    XCD: string
    XDR: string
    XOF: string
    XPF: string
    YER: string
    ZAR: string
    ZMK: string
    ZMW: string
    ZWL: string
  }
  
  
